Module4 task1
htmlacademy-adaptive/1842859-pink-24 pull request #5
Opened 2021-12-16 18:09 UTC by SitnikovaIrina

Проблему с растягивающимися фоновыми изображениями я так и не решила. Оставила пока как есть, дождусь лайва на эту тему. В планшетной и декстопной версии в header блоки nav и download, спозиционированы абсолютно и из-за этого при растягивании окна они уезжают. Они все разные блоки, хотя находятся в header. Пока не могу найти решение этой проблемы

2021-12-17 09:29 UTC, Dima-Dim requested changes
После правки по комментариям не забудь проверить бем https://yoksel.github.io/html-tree/

2021-12-17 20:58 UTC, SitnikovaIrina commented on source/index.html
> +            <ul class="nav__list">
Пока что точно не знаю. Я никак не могу решить как правильно спозиционировать этот блок

2021-12-17 20:59 UTC, SitnikovaIrina commented on source/index.html
> +            <div class="research__container">
Я не смогла правильно расположить блок без дополнительного контейнера

2021-12-20 09:44 UTC, Dima-Dim requested changes
Убрать из медиа выражения свойства которые не меняются.

2021-12-20 09:44 UTC, Dima-Dim commented on source/index.html
> +            <button class="download__button" type="button">Скачать приложение</button>
Кнопка в ссылке?

2021-12-20 09:44 UTC, Dima-Dim commented on source/sass/components/advantages.scss
> +    background-image: url("../../img/png/grey-background.png");
`../../` -> `../`

2021-12-20 09:44 UTC, Dima-Dim commented on source/sass/components/advantages.scss
> +    margin: 0 auto;
Если значение свойства не изменилось, то не нужноего заново описывать в медиа выражении.

2021-12-20 09:44 UTC, Dima-Dim commented on source/sass/components/research.scss
> +.research {
Для соблюдения логи лучше блок описывать в начале, потом его модификаторы, далее элементы с модификаторами. Т.е. примерно так, как они стоят в разметке по вложенности.

2021-12-21 07:59 UTC, merged